<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DMS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4ac4d5bf-9f52-4596-8efb-9c9d8cdfd65d</testSuiteGuid>
   <testCaseLink>
      <guid>605a84aa-e0d2-4911-87ac-c34c76db83e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FROMScaleSupport/SRC-22134_ContractHavingAPCWithFROMScales</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adb25fa0-77c8-40bf-be4f-c24ec9715ace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d046654d-b6c7-4599-8abc-72442ff841e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db1b3ed8-3d04-4ac9-8a3a-c88c281a4c28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91347f0f-45be-4dc6-8c4d-19dc34a4d662</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
