<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S4_DMS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0517f85b-1032-48fa-9bb8-feb8d7ddf35b</testSuiteGuid>
   <testCaseLink>
      <guid>37a73730-15ff-4916-9df5-2cca63a7dd85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/UtilTests/APC_PreRequisites</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>39b47535-eb5e-48cb-8648-5ec994023fdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/CleanSheet/DMSTC-2292_CreateSourcingEvenWithCleanSheet</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4e37cf56-916a-4330-bbc7-93bc5509b202</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/CleanSheet/DMSTC-2301_CleanSheet_NewLineItemAdditionatSupplierSide</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>10826c7d-284f-42d1-a8a1-ad1eeebdcd03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/CleanSheet/DMSTC-2955_VerifyCostGroupTermsinSourcingExternalApprovalAPI</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5c1b6655-9205-49b5-8df8-4aa90fd70572</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/CleanSheet/DMSTC-2946_Verify Cost group terms are reportable as a part of Analytical report</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ed91676e-0dbd-478e-a49c-078d61169c9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/MasterDataServices/DMSTC-2638_DMSTC-2639_VerifyMasterDataEntities</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afd60f4b-ba19-4d5c-a0bb-2010f5f6004e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07a188af-0600-4bf7-bd91-2ab866795c61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/MasterDataServices/DMSTC-2637_CreateERPWithS4HANA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a572dbf0-eeb6-49fe-b07b-3cbfe3d7ca29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9ac5088-cedf-42f6-8bf7-33d292683e0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FormulaSupport/ACM-9854_AppendContractFromEventContent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2033e16b-4764-4e90-8ca5-133cb7721196</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00287d94-2788-49ea-8e88-d0e8dc0d42bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>667181e0-e5b0-4899-87f6-79dbc369d0ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>112ec40d-1551-49f6-b336-ce88867f3061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c2ddf59-592c-4b34-98bf-325cce7d09fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a2b2bbc-4053-4e0a-96b5-4857cab01593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bff1750-1902-4b3d-891a-080a880253e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48cb85a2-e67d-4da7-b692-6629a36a0859</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aeeff25-9004-4fae-b34a-6f7246047d64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84146efd-dbf6-40f6-9532-01b8d18c86a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>733f708d-793a-4cea-aca2-aa534b200ac7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e191332-1bc2-4421-9362-cce3acac6717</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FormulaSupport/SRC-21894_ContractHavingAPCWithFormulaSupport</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fa23b59-13ff-462e-8abf-2911d887166d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>988d9423-c1dc-44a2-876f-19c26212df5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e9a6e84-8f17-4c6a-a060-c0224c1bfdf4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2496086-a74a-4f4b-9fb2-9096b5c1a347</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a72667d-7dff-44cf-a196-823917d8a3e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FormulaSupport/SRC-21890_CreateContractFromEventWithFormulaSupport</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81cb1fde-97d9-4c03-ad72-825ab1f09f2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c5df520-1ffa-40b5-9a0b-be4f89967a76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd4bc8c8-b592-45fe-b38e-8830ada3d57c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17de5a50-7362-4388-9fc8-1ddb3b18b1c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72a34765-a4b0-4852-b8f9-3e70e41f3bf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e555c9ab-b271-4891-84c2-886de059a22c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e93f6a76-f6de-4062-bd7d-5f4c2f35fea6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>551392c3-e444-497a-84dd-98b8debeae92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FormulaSupport/ACM-9855_ReplaceContractFromEventContent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>403e8955-ccaa-4190-9500-b2b6a39660f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c42ce61-4c0a-4586-a39a-2aae3ab202dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>823e03a2-08e2-497f-ad6c-6851fef550b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c17edb9a-d000-498f-8cdd-bae8fa4e22d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>610bfa85-be4e-4661-b77b-a95c73cdb7b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c3dc8fa-6b0b-4813-aec0-0b6bccc5a3e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f95f151-be70-4674-a2df-9d825744dc95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11d9379f-1994-40ac-85c0-889f5d1a7f19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>893df906-b5a8-4c13-85d4-9f9fe3c6315a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bed3027e-70f3-4520-923c-2be4235bf6f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c4aac39-3b9a-4b0a-98ad-46c6e55d1e54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a0a2ea1-80cd-4cbb-8e22-8065f3c7ba2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FROMScaleSupport/SRC-22134_ContractHavingAPCWithFROMScales</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adb25fa0-77c8-40bf-be4f-c24ec9715ace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d046654d-b6c7-4599-8abc-72442ff841e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db1b3ed8-3d04-4ac9-8a3a-c88c281a4c28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91347f0f-45be-4dc6-8c4d-19dc34a4d662</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>039b7ec0-a008-422d-b277-15ae0bef2d9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FROMScaleSupport/SRC-22125_CreateContractFromEventWithFROMScale</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b22fc64-3cd5-4746-b116-5fdd7737ba52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098f9232-f491-4aa8-ad26-8245ce9c9e2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d375d11b-f238-44dd-84de-7b7e0b96e79b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>386214f9-517d-4e94-bf63-3d9b313ee8f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e40ead92-7f56-4d77-91e1-7c13ec349777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>761897f8-0be2-4768-bdef-5839d74b1278</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50913a5e-6612-4f8e-88dc-77e442fca8c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d46696a2-8421-44ec-adbf-0b7bc46ebb47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FROMScaleSupport/ACM-9855_ReplaceContractFromEventContentFromScale</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fc213f2-1df8-4250-abe6-539ebf7a1896</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7325e944-00cf-4ffb-ad8e-70e52e9aedee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9bf568e-58c3-447b-be89-702ad6947c17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa062fc7-13cf-46eb-a142-1258889bccfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9515d9d6-3cc8-46a0-b7ee-8dcd8bba9d11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f7ad26b-5b4b-40e7-a9df-04a3d5a4a512</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3afd84c-2847-4a6a-8221-c8412035348f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>116ed303-ca7e-4fe8-8fe0-74de3eee2f5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d1ed6b6-5ce3-485f-9ec3-26d54190efcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c78a0277-42c4-4698-8988-08ab16877fef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cda7e3ea-450a-4654-a0ca-7206822a62ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dad027e8-ad42-4cb4-ade5-c03bd409f4d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingCondition_FROMScaleSupport/ACM-9854_AppendContractFromEventContentFromScale</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e11fdfbe-d9af-4ae8-bc37-41609d698a5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b07e1f1e-0e92-47fc-ba2c-7dd259a5c363</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2032d20e-2039-46cf-9735-073c026fc464</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>634a5983-ae67-4300-9f09-87c4103eec52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2d3cf8b-0ca8-4fcd-ad05-671196366abf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbd3c8f2-1a50-48c8-a0db-e4ff1ed3230a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec490a0a-9da1-4371-8f28-f5dac996b0d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beba1db9-3f8a-4a33-9500-210f4929b48e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72351a45-1cbb-4b80-a5e0-aa6afecc885d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9016dcb3-a436-4db8-bc8f-3879ffd1208f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7296d337-dccf-4fa6-b834-cd8dde262f28</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0dd7da29-69d1-4892-a8b5-ecbe0a8eaf6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/Regression_AdvancedPricingCondition/AppendContractWithAPCFromEventWithoutAPCBothLineAndHeaderLevel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f44539b-706b-4335-8831-826ef6044555</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6b4b2ba-9be4-4e8d-a80e-93b18ad6bb86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec3e359f-84c2-4a2b-b9ca-554857d5824b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>101cb49c-18d1-49b4-9319-0a87a63fb523</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6843f724-ee00-4ffd-800d-3acc49b7c91f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3cf699f-7e0a-40e6-a5e4-6e3bb77b4963</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b616f62-5fa3-4e38-b421-ea34729233a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c24dc35-26c9-4224-9444-8f3b2db04cd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eda2bf5f-b1ed-4f02-ab1b-b8a25ab1ab66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e7c6882-ecf0-45fb-b22c-afc9d2d91a40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a93921c-3ec6-4620-8486-2be08f9a3629</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3d38708-649f-4317-b0cc-d7375efab944</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/Regression_AdvancedPricingCondition/DMSTC-2704_APCRuleEditabilityAtCLIDHeaderAttribute</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f870aea-fe82-4200-a877-3f8780675db5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb205d8b-53e3-4917-afa5-0abb7560d009</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2800d29-4b42-46d3-959c-aaaa9124b58e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/Regression_AdvancedPricingCondition/DMSTC-2615_AppendAPCContractFromSimplePriceEventContent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c24a8e5c-6252-493c-b7c0-f300626e0b21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5deb3e98-d887-4ccd-8cb3-bdabe6b6f710</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c27e8da-fe77-40ad-ad4a-7d325faab087</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ded9a40-f6d5-4dc0-8b1b-db4e4621e77f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f98ccfc-3919-45d2-9d30-fa8081e2c005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3939297-cdda-4c89-9c14-2e71d55261ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04c573a4-d244-4db7-87b4-487ff19cba54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82c44111-e84e-4940-bace-21c0497ac20d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9770ad6f-c0b4-4c34-95cd-f7e8ea898680</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a8afdd6-eed8-4f45-899b-c089526a72b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd1c7c8-0772-4121-b71d-fed9fee8a76f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48ac7094-e827-41c4-b4c7-3dd55b5777ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/Regression_AdvancedPricingCondition/ReplaceContractWithAPCFromEventWithoutAPCBothLineAndHeaderLevel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62525687-ad98-43a4-a511-71bde5219bda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>139cbc32-23b6-41bb-a9da-6f28713ea157</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e12b48c-b2a5-438b-8bb2-b88932c22008</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceab69d6-3f98-44e5-b45a-93c3855d1722</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e29f76b-a2a7-49ee-81bd-122e12891324</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfbcbc9-8bfb-48d4-ae22-fa4ca463c662</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>028d80da-a59b-4af9-a5a9-2055ed888d95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f405331d-f98a-4c66-95b9-24080fda33cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>113f5d80-7c2c-4ada-b8d3-8e62ebd287dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aded0ea-c400-4e39-9b90-94bad1aba1c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef178b33-d5a1-4e8c-9e91-ee27ccf32355</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20951660-fb9d-4a19-84ae-b824b8ae4da1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/Regression_AdvancedPricingCondition/CreateEventWithHavingAPCLines</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a800886-4840-4527-9115-f6a6f72e1dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8ace202-9959-44c5-ba16-850ee91bc0f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eae78c8-1cf2-4123-ad53-326b0496c329</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a4f89a3-6692-4852-ae43-1a933df13ee3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>836e6b1c-b255-4e57-a8fd-7acf00faf51a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fa24e5c-b291-4d4d-9de2-5a9482ccaa32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f51fbe7-120f-4ae0-a33a-252bdf7e29ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea877267-ab9f-4471-9c05-e768463e5c8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/Regression_AdvancedPricingCondition/CreateContractFromEventWithNonAPCLines</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>874501cb-b291-4d32-ac16-49b6e0931e49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce3f29ab-03a8-48c1-aca0-ac2cf43d8b70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e623687-8b28-4130-9c11-d95ce99430a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f39d8643-8a7d-4d2c-9ffb-318db792c653</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4386dc2f-80db-4113-acb3-9fa3fcb65408</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a75b8c-1754-495e-aa92-5602fd5eb306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8c9822a-1bd6-4dbc-bf5a-b839c38da321</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9343010d-c3fa-49cc-8ab3-cc4e876f4bb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/Regression_AdvancedPricingCondition/DMSTC-2614_ReplaceAPCContractFromSimplePriceEventContent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b7fc80a-2d61-46f4-87fc-b24d8e5bed25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acd2ed49-8039-4198-af59-3a49f30b3b03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b72f9ce9-ab58-4d64-a4fe-45bf8c285330</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a424377-96dc-4392-bdb2-ced7aff22f67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24362df3-0736-4069-8ae1-e3e9b581d0ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a48acf3-c9ce-4e45-8061-fcfc5b16f831</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>237de185-1a52-41dc-a339-b1d978e0b8c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79fca2c9-1274-4db6-95d9-f152ed7e531e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>789847d2-47cf-4708-8b19-f686df684f55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1f7d691-c9e2-4a60-ba3c-318dddac521d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad1fd213-d084-46a8-8e2a-47566d570952</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
