<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>20078400-b85f-4a9e-b256-3791ae680eef</testSuiteGuid>
   <testCaseLink>
      <guid>23c0ee50-af46-4fb2-b223-2cc84b00fec4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DMS/PricingConditionSupportForLots - Copy/DMSTC-3002_ContractHavingLotWithAPCTerm</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3783da3-d08e-4261-bb00-08ec9830d5e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3e56a3e-7f34-4f04-aec9-6e78b66a2143</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1b3ab7e-4f2c-44af-877d-4907903eb650</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>139bcc8c-5426-4eff-b58a-33ae8d896c72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7c4d141-b47b-4eec-acb8-a6c7c5045236</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DMS/PricingConditionSupportForLots - Copy/DMSTC-2917_DownloadBidComparisonWithAPCLot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9adfc3bc-5958-4463-967c-774cb01cf166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9140c50-a77c-4292-91bf-01bb8e0461a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e90ca59-e916-45d4-a7ee-5a17b32a9ea0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>598b9394-8e8e-4a71-b023-2e4eacc34fe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65051bad-d8c2-4a03-aca7-84661a68b255</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcbea9a2-7f8d-4927-be9e-9b9ac9dd41c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59acee4f-c979-426e-a3f9-44225fe1db44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef375c57-e5ef-48d1-8758-9d5a0183d5d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DMS/PricingConditionSupportForLots - Copy/DMSTC-2920_CreateContractFromEventContentWithAPCLot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc86bd1a-43e5-43aa-8c0b-b5a6d5c3781f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cb89d56-a533-4139-b61d-41f38ba8d9e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ee4bb32-5f28-41df-bce4-533c0269f1e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba907a23-fa01-4325-9eef-d5a4dd5f980b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>934fb531-ed41-44b0-92ac-b00d8df51516</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9c1bf54-d15f-4a1b-8bf4-9a75c064b846</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6ff5e2-55b3-46f5-b2d0-b99839f52bbf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c160704a-7d42-4f5e-b017-2b508a9d11b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DMS/PricingConditionSupportForLots - Copy/DMSTC-2922_AppendContractFromEventContentHavingAPCLot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1426ffcb-fa0c-467e-838f-64c2c646d4db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1f47f92-3b12-4d63-89c6-bb8f6ecc4eb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4052f7a2-13b8-443d-86a1-7dcfafd80082</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17cf2439-ed6b-49e2-b5bc-89c7b5cd0cb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80577ff8-6b91-40a8-b809-f782a06d7a73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25c187c6-6e84-41ec-b802-a67418b54070</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35367e36-7915-454e-aaee-fdb5c445ce87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2768fb-b18b-469a-b345-4262ef5029ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6269fd2c-58d5-4dff-bf4d-ba688db2688e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14ace96a-2691-4803-88a6-82bd7578ae24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b6fd746-7cc0-4c32-ac29-69a78e9ee041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f557ccc2-668a-4e36-ad4d-8e70cc8bda56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DMS/PricingConditionSupportForLots - Copy/DMSTC-2915_CreateEventHavingBasketLotWithAPCTerms</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cce87626-43fd-4b63-a74d-a0e62b2e89e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c77917-b297-4511-b9d2-5604d0ecb70c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9bad7d2-0023-4d5c-ab0d-2f00ecfb71b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3359e689-833f-4a8c-afc3-d367bbf5f575</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1703052-fa27-4216-8e63-627b435aa3de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbe1332b-8509-43c5-b98d-051f121961d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab62af49-7636-4ef6-81d4-d99036cc38b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83afc2a9-49db-44a0-a3ee-f67150c34191</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DMS/PricingConditionSupportForLots - Copy/DMSTC-2923_SourcingFollowOnProjectFromContractshavingLotAPCTerm</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d95040-315a-44fc-ac17-16fcbeb04946</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84eaeb4f-4818-4253-806d-57c7dd42234c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f3bf598-84f2-43a6-8012-e616f124b05a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cd0e36b-59b4-4a74-b98e-852193100b56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b449bb5-7344-4301-b736-98e521af13cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a53f523d-10de-49e8-9fa7-b86ea398e4df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b3f3b9b-9ed3-4395-add7-794626c1df12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DMS/PricingConditionSupportForLots - Copy/DMSTC-2921_ReplaceContractFromEventContentHavingAPCLot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>225c890b-02d4-4eed-9975-b80702ec31f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4088dbce-1d19-4b5a-ac7a-08f8ec77dcb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa9ddeeb-da89-478d-9044-d01c181e97a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe87e691-6ac4-4709-b1a6-9cc5feb8fc10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb1c6cad-2221-49a1-a9ca-da16e52f5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2819a355-1ff7-449e-9e29-8ac28e6d017b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2af4f89-fb03-4417-b918-2a973bd71cdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c1725f7-b708-46bf-bae3-5ef1b7511cba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ff16610-c376-4777-883d-51389c8dd2f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3e83991-14ad-421b-bbf5-2d4f0f9d3bcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7b9c73e-f792-4c70-945a-e9a28a2e4836</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>688ccbe7-1909-4aef-9538-b3459ed4c4e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DMS/PricingConditionSupportForLots - Copy/DMSTC-2916_EventContentSheetExport</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bfdc3a4-7e15-4c93-a447-31ac8683f030</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a060a1-8a9c-4e2d-be13-bcef07e32c0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>773abe43-0c0b-405d-a1ef-2466859374a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b39ec948-1220-46cf-bc12-628a50bd89d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf2df5d-8ad5-489e-8fe0-5c101eb54dec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25aa4c75-ffe9-4cd5-9661-c5b760ebae6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e81c3dc5-1348-4a7c-a5b9-4605a8289ff6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
