<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AmendContractAttribute</name>
   <tag></tag>
   <elementGuidId>b566697f-6f80-44f2-87b9-d2c74bd727f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>ContractWorkspaceSummaryPanel:amendAction</value>
   </webElementProperties>
</WebElementEntity>
