<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>approveDocumentTaskItemAction</name>
   <tag></tag>
   <elementGuidId>ec019794-814b-4787-8e5b-09491c01161f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>Approval::AbstractDocumentDownloadIcon:itemAction</value>
   </webElementProperties>
</WebElementEntity>
