<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>duedatePhase</name>
   <tag></tag>
   <elementGuidId>f60291db-8bc6-410a-9e8b-2520b3164b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>DueDate_selectedOption::DateOffsetAfterPhase:container.offset</value>
   </webElementProperties>
</WebElementEntity>
