<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_w-rdo w-rdo-dsize_1 (5)</name>
   <tag></tag>
   <elementGuidId>28032b02-4524-49b1-9b7d-ee1cc288ad6a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bh</name>
      <type>Main</type>
      <value>RDO</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-rdo w-rdo-dsize</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>IsTest_selectedItem::CreateView_IsTest:currChoice_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awmousedown</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_jnhald&quot;)/td[@class=&quot;ffp&quot;]/table[@class=&quot;cueT&quot;]/tbody[1]/tr[1]/td[1]/span[@class=&quot;w-rdo-list&quot;]/label[2]/div[@class=&quot;w-rdo-container&quot;]/label[@class=&quot;w-rdo w-rdo-dsize&quot;]</value>
   </webElementProperties>
</WebElementEntity>
