<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>overViewActionsPopUpLink</name>
   <tag></tag>
   <elementGuidId>b482a6d4-433e-44b8-9a0d-8c47d34840b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>TemplateOverviewPanel:PopupMenuLink</value>
   </webElementProperties>
</WebElementEntity>
