<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchFieldsChooserspecialOthersAction</name>
   <tag></tag>
   <elementGuidId>64a1e6e5-c4f2-41b7-89cc-f6e2cec914dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>SearchFieldsChooser:specialOthersAction</value>
   </webElementProperties>
</WebElementEntity>
