<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Duration__4qp5_b</name>
   <tag></tag>
   <elementGuidId>d80ad205-5de9-4169-bcc7-bc8c874d62ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@div = 'input' and @awname = 'PlannedEndDateComposition_selectedOption::ASCTimeDuration:offset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>div</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>PlannedEndDateComposition_selectedOption::ASCTimeDuration:offset</value>
   </webElementProperties>
</WebElementEntity>
