<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___dol9xc</name>
   <tag></tag>
   <elementGuidId>e7692fbe-2830-4313-aa34-b9b5e0aa642d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@awname = 'PlannedBeginDateComposition::EditView_PlannedBeginDateComposition:textFieldAction_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>PlannedBeginDateComposition::EditView_PlannedBeginDateComposition:textFieldAction_3</value>
   </webElementProperties>
</WebElementEntity>
