<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setWorkSpaceToContextPageLink</name>
   <tag></tag>
   <elementGuidId>9eb8d71c-54d5-4cfd-8951-53000b3acd73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>setWorkspaceToContext::TestCategoryLinks:testUnitClick</value>
   </webElementProperties>
</WebElementEntity>
