<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Display__p7ugj</name>
   <tag></tag>
   <elementGuidId>9709e068-faaa-418f-96b3-94e19b0bdc03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@awname = 'class=test.ariba.sourcing.selenium.ViewPreferenceTestDestager$SetProjectViewArg_display_field=display_selection_CompactView::RadioButtonList:value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>class=test.ariba.sourcing.selenium.ViewPreferenceTestDestager$SetProjectViewArg_display_field=display_selection_CompactView::RadioButtonList:value</value>
   </webElementProperties>
</WebElementEntity>
