<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>regionFieldMatch</name>
   <tag></tag>
   <elementGuidId>f77d43b9-193b-4708-9684-93d16a541ae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>Expression_CB-2-0_Region::CreateView_Expression:selectGroupField</value>
   </webElementProperties>
</WebElementEntity>
