<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RepeatDocumentDraftEditView</name>
   <tag></tag>
   <elementGuidId>1c820e2e-cc02-4996-b76b-f68734224b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@awname = 'IsPerDocumentDraft_selectedItem::EditView_IsPerDocumentDraft:currChoice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>IsPerDocumentDraft_selectedItem::EditView_IsPerDocumentDraft:currChoice</value>
   </webElementProperties>
</WebElementEntity>
