<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_validationMethodtest.</name>
   <tag></tag>
   <elementGuidId>c5849148-1378-4100-8eb1-85e29f8db3a9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>var fnc=function(){ariba.Dom.limitTextLength(this,0);}; setTimeout(fnc.bind(this),250)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ParameterStringToCompare</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-txt-active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bh</name>
      <type>Main</type>
      <value>TA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_ml</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ParameterStringToCompare</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>AUTOMATION_VALIDATION_READ_STRING</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{&quot;validationMethod&quot;:&quot;test.ariba.sourcing.selenium.validator.SPMTestValidator,validateTasksTab,ariba.sourcing.content.SPMProject,ariba.sourcing.content.SPMProject&quot;,&quot;validationParameters&quot;:&quot;{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;CUP-23543\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;In Progress\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;CUP-23543 To Do Task one EDITED(Round 1)\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Owner\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Project Owner\&quot;,\&quot;key\&quot;:\&quot;Owner\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Observer\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;[]\&quot;,\&quot;key\&quot;:\&quot;Observer\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Template\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543 To Do Task one EDITED(Round 1)\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;CUP-23543 To Do Task Two(Round 1)\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Owner\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Project Owner\&quot;,\&quot;key\&quot;:\&quot;Owner\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Observer\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;[]\&quot;,\&quot;key\&quot;:\&quot;Observer\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Template\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543 To Do Task Two(Round 1)\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;CUP-23543 (Feb 2019)\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Complete\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;CUP-23543 To Do Task one(Round 1)\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Owner\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Customer Support Admin\&quot;,\&quot;key\&quot;:\&quot;Owner\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Observer\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;[]\&quot;,\&quot;key\&quot;:\&quot;Observer\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Complete\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543 To Do Task one(Round 1)\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;CUP-23543 To Do Task Two(Round 1)\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Owner\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Project Owner\&quot;,\&quot;key\&quot;:\&quot;Owner\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Observer\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;[]\&quot;,\&quot;key\&quot;:\&quot;Observer\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Not Started\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543 To Do Task Two(Round 1)\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543 (Feb 2019)\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;CUP-23543 (Mar 2019)\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Complete\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;CUP-23543 To Do Task one EDITED(Round 1)\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Owner\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Customer Support Admin\&quot;,\&quot;key\&quot;:\&quot;Owner\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Observer\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;[]\&quot;,\&quot;key\&quot;:\&quot;Observer\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Complete\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543 To Do Task one EDITED(Round 1)\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;CUP-23543 To Do Task Two(Round 1)\&quot;,\&quot;list\&quot;:true,\&quot;value\&quot;:{\&quot;validationParameters\&quot;:[{\&quot;name\&quot;:\&quot;Owner\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Customer Support Admin\&quot;,\&quot;key\&quot;:\&quot;Owner\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Observer\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;[]\&quot;,\&quot;key\&quot;:\&quot;Observer\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false},{\&quot;name\&quot;:\&quot;Status\&quot;,\&quot;list\&quot;:false,\&quot;value\&quot;:\&quot;Complete\&quot;,\&quot;key\&quot;:\&quot;Status\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543 To Do Task Two(Round 1)\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]},\&quot;key\&quot;:\&quot;CUP-23543 (Mar 2019)\&quot;,\&quot;objectList\&quot;:false,\&quot;validateOrder\&quot;:false}]}&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ParameterStringToCompare&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//textarea[@id='ParameterStringToCompare']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//form[@id='_rlkbfc']/table[2]/tbody/tr/td[2]/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parameter String to Copy to Test'])[1]/following::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete'])[5]/following::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Validation String from Replay'])[1]/preceding::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::textarea[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//textarea</value>
   </webElementXpaths>
</WebElementEntity>
