<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AmendmentType-Amendment</name>
   <tag></tag>
   <elementGuidId>e58c340b-0996-404c-99b7-7210f2fc27eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>AmendmentReason::AmendmentView_AmendmentReason:itemList_label_Amendment</value>
   </webElementProperties>
</WebElementEntity>
