<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cwsPublishButton</name>
   <tag></tag>
   <elementGuidId>70522e21-9d6d-4a04-b9d9-9c3fd7f601cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>ContractWorkspaceSummaryPanel:publishAction</value>
   </webElementProperties>
</WebElementEntity>
