<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>reviewDocumentItemAction</name>
   <tag></tag>
   <elementGuidId>48ee4c84-f333-4547-a824-785ffebd0e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>Review::AbstractDocumentDownloadIcon:itemAction</value>
   </webElementProperties>
</WebElementEntity>
