<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Most_Recent_Label_2</name>
   <tag></tag>
   <elementGuidId>aa8b302b-b787-40d7-abf3-9f7846c6bb1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>awname</name>
      <type>Main</type>
      <value>ReportTimePeriod:RelativeDurations_label_2</value>
   </webElementProperties>
</WebElementEntity>
